from tkinter import*
def b1_click():
    n=int(entry1.get())
    entry2.delete(0, END)
    entry2.insert(0, str(int(n/60)))
    entry3.delete(0, END)
    entry3.insert(0, str(n/60*0.0005))
root=Tk()
root.title('Збережи дерево')
text1=Label(text='Введіть масу, кг:')
text1.grid(row=0, column=0, padx=8, pady=8)
entry1=Entry(width=10)
entry1.grid(row=0, column=1, padx=8, pady=8)
b1=Button(text='Обчислити', width=14, command=b1_click)
b1.grid(row=1, column=0, columnspan=2, padx=8, pady=8)
text2=Label(text='Збережено дерев:')
text2.grid(row=2, column=0, padx=8, pady=8)
entry2=Entry(width=10)
entry2.grid(row=2, column=1, padx=8, pady=8)
text3=Label(text='Збережено лісу, га:')
text3.grid(row=3, column=0, padx=8, pady=8)
entry3=Entry(width=10)
entry3.grid(row=3, column=1, padx=8, pady=8)
root.mainloop()
